import localFont from "next/font/local";
import "./globals.css";
import BottomNavbar from "./components/BottomNavbar";
import ProfileNavbar from "./components/Navbar";
import { UserProvider } from "@/context/UserContext";
import { Toaster } from "sonner";
//  D:\New folder (2)\original_mahul\app-frontend\src\app\layout.js

import { faRepeat } from "@fortawesome/free-solid-svg-icons";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#F8F9FA] overflow-x-hidden antialiased`}
      >
        <UserProvider>
          <ProfileNavbar />
      {/* <div>{children}</div>  */}
<div className="min-h-screen">
        <main className="p-4">
          {children}
        </main>
      </div>
          <Toaster position="top-center" />
          <BottomNavbar />
        </UserProvider>
      </body>
    </html>
  );
}
