import localFont from "next/font/local";
import "./globals.css";
import BottomNavbar from "./components/BottomNavbar";
import ProfileNavbar from "./components/Navbar";
import { UserProvider } from "@/context/UserContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#F8F9FA] overflow-x-hidden antialiased`}
      >
        <UserProvider>
          <ProfileNavbar />
            {children}
           <BottomNavbar />
        </UserProvider>
      </body>
    </html>
  );
}
